---
- name: Execute bundle install
  shell: bash -lc "bundle install"
  args:
    chdir: "{{ app_dir }}"

- name: Set application.rb from template
  template:
    src: application.rb.j2
    dest: "{{ app_dir }}/config/application.rb"

- name: Set puma.rb from template
  template:
    src: puma.rb.j2
    dest: "{{ app_dir }}/config/puma.rb"

- name: Set puma.service from template
  become_user: root
  template:
    src: puma.service.j2
    dest: "/etc/systemd/system/puma.service"

- name: Reload systemd
  become_user: root
  systemd:
    daemon_reload: yes

- name: Start MySQL service
  become_user: root
  service:
    name: mysqld
    state: started

- name: Execute bin/setup
  shell: bash -lc "bin/setup"
  args:
    chdir: "{{ app_dir }}"

- name: Precompile assets
  shell: bash -lc "RAILS_ENV=development bundle exec rails assets:precompile"
  args:
    chdir: "{{ app_dir }}"

- name: Create sockets directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "ec2-user"
    group: "ec2-user"
    mode: "775"
  loop:
    - "{{ app_dir }}/tmp/sockets"
    - "{{ app_dir }}/tmp/pids"
