---
- name: Check rbenv
  shell: bash -lc "rbenv --version"
  register: rbenv_exists
  changed_when: false
  ignore_errors: true

# Install rbenv and ruby-build
- name: Clone rbenv repository
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: rbenv_exists is failed

- name: Pass rbenv path
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
    create: true
  when: rbenv_exists is failed

- name: Initialize rbenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'
    create: true
  when: rbenv_exists is failed

- name: Source bash profile
  shell: bash -lc "source /home/ec2-user/.bash_profile"
  when: rbenv_exists is failed

- name: Clone ruby-build repository
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build
  when: rbenv_exists is failed

- name: ruby {{ ruby_version }} installed check
  shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: true

- name: Install Ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: ruby_installed is failed

- name: changed ruby {{ ruby_version }}
  shell: bash -lc "rbenv global {{ ruby_version }}"
