# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# 参考：https://circleci.com/developer/ja/orbs/orb/circleci/aws-cli
orbs:
  aws-cli: circleci/aws-cli@5.2.0
  ansible-playbook: orbss/ansible-playbook@0.0.5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cloudformation:
    # orbs使う時はexecutorとする
    executor: aws-cli/default
    steps:
      # Checkout the code as the first step.
      - checkout
      # https://circleci.com/developer/ja/orbs/orb/circleci/aws-cli のsetupを使う
      - aws-cli/setup:
          # 下記の環境変数はcircleci実行時に設定する
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to aws from template
          command:  |
            set -x
            aws cloudformation deploy --template-file cloudformation/cfn_network.yml --stack-name circleci-network
            aws cloudformation deploy --template-file cloudformation/cfn_iam_role.yml --stack-name circleci-iam-role --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation deploy --template-file cloudformation/cfn_application.yml --stack-name circleci-application --capabilities CAPABILITY_NAMED_IAM
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:5xYMYiXExMetTl9FUX/tiLxVy0QjrR0oqb50dx/MA7U"
      - ansible-playbook/install:
          version: 2.10.7
      - run:
          name: Get RDS password from AWS Secrets Manager
          command: |
            DB_PASSWORD=$(aws secretsmanager get-secret-value \
              --secret-id aws-lecture13-ci-rds-secret \
              --query 'SecretString' \
              --output text | jq -r '.password')
            echo "export DB_PASSWORD=${DB_PASSWORD}" >> $BASH_ENV
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -i ansible/inventory
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  iaas-pipeline-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation
