# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# 参考：https://circleci.com/developer/ja/orbs/orb/circleci/aws-cli
orbs:
  aws-cli: circleci/aws-cli@5.1.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cloudformation:
    # orbs使う時はexecutorとする
    executor: aws-cli/default
    steps:
      # Checkout the code as the first step.
      - checkout
      # https://circleci.com/developer/ja/orbs/orb/circleci/aws-cli のsetupを使う
      - aws-cli/setup:
          # 下記の環境変数はcircleci実行時に設定する
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to aws from template
          command:  |
            set -x
            aws cloudformation deploy --template-file cloudformation/cfn_iam_role.yml --stack-name circleci-iam-role

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  iaas-pipeline-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - execute-cloudformation
