---
- name: remove the MariaDB
  become_user: root
  yum:
    name: mariadb-*
    state: absent

- name: install the mysql rpm from a remote repo
  become_user: root
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present

- name: Import MySQL GPG key
  become_user: root
  shell: rpm --import "https://repo.mysql.com/RPM-GPG-KEY-mysql-2023"

- name: install mysql-community-server
  become_user: root
  yum:
    name:
      - mysql-community-server
    state: present

- name: Set database.yml from template
  template:
    src: database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"
  become_user: root

- name: Start MySQL service
  become_user: root
  service:
    name: mysqld
    state: started
