---
- name: Check nvm installed
  shell: bash -lc "nvm -v"
  register: nvm_exists
  changed_when: false
  ignore_errors: true

- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: /home/ec2-user
    creates: /home/ec2-user/.nvm/nvm.sh
  when: nvm_exists is failed

- name: Check node installed
  shell: bash -lc "node -v | grep {{ node_version }}"
  register: node_version
  changed_when: false
  ignore_errors: true

- name: Install node
  become: no
  shell: >
    . /home/ec2-user/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: /home/ec2-user
    creates: /home/ec2-user/.nvm/versions/{{ item }}
  loop:
    - "{{ node_version }}"
  when: node_version is failed

- name: Check yarn installed
  shell: bash -lc "yarn -v | grep {{ yarn_version }}"
  register: yarn_version
  changed_when: false
  ignore_errors: true

- name: Install yarn
  shell: bash -lc "npm install -g yarn"
  when: yarn_version is failed

- name: Set yarn version
  shell: bash -lc "yarn set version {{ yarn_version }}"
  when: yarn_version is failed
