- hosts: all
  become: yes
  tasks:
    - name: Update yum
      yum:
        name: "*"
        state: latest
    - name: Install git
      yum:
        name: git
        state: present
        lock_timeout: 180
